version: '3.8'

services:
  node:
    build:
      context: .
      dockerfile: DockerFile
    ports:
      - '5000:5000'
    env_file:
      - .env
    volumes:
      - .:/usr/src/app
    networks:
      - app-network

  nginx:
    build:
      context: .
      dockerfile: DockerFile.nginx
    ports:
      - '80:80'
    depends_on:
      - node
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
